"""
AxiomGuard Tournament — Multi-strategy rule derivation with Z3 conflict detection.

Solves the "blank-page problem" of BYOR: instead of writing YAML from scratch,
generate competing candidate rules from source documents using multiple extraction
strategies, surface conflicts via Z3, and let humans arbitrate.

Trust model:
  - LLM: untrusted (generates candidates)
  - Z3: trusted (proves conflicts)
  - Human: authority (picks winners)

Usage::

    from axiomguard.tournament import Tournament

    tourney = Tournament(
        source="นโยบายสินเชื่อส่วนบุคคล...",
        domain="personal_loan",
    )

    tourney.generate(llm_generate=my_llm_fn)
    conflicts = tourney.detect_conflicts()

    for conflict in conflicts:
        tourney.decide(conflict.id, action="pick_winner", winner_id=0)

    for c in tourney.standalone_candidates():
        tourney.approve(c.id)

    kb = tourney.to_knowledge_base()

Academic foundation:
    Resnik (2025), "Large Language Models Are Biased Because They Are
    Large Language Models", Computational Linguistics.
"""

from __future__ import annotations

import hashlib
import re
from datetime import datetime, timezone
from itertools import combinations
from pathlib import Path
from typing import Any, Callable, Dict, List, Literal, Optional

import yaml
from pydantic import BaseModel, Field

from axiomguard.knowledge_base import KnowledgeBase
from axiomguard.models import Claim
from axiomguard.parser import (
    AxiomParser,
    DependencyRule,
    ExclusionRule,
    RangeRule,
    Rule,
    UniqueRule,
)
from axiomguard.rule_generator import _RULE_GEN_PROMPT, _clean_yaml_output, _validate_yaml


# Z3 timeout defaults for tournament operations (milliseconds).
# Override by passing timeout_ms to KnowledgeBase.verify() calls.
Z3_CONFLICT_TIMEOUT_MS = 500
Z3_REDUNDANCY_TIMEOUT_MS = 200

# =====================================================================
# Strategy Prompt Directives
# =====================================================================

STRATEGY_DIRECTIVES: dict[str, str] = {
    "constraints": (
        "## Focus: Hard Constraints\n"
        "Extract ONLY rules that represent hard constraints — things that "
        "MUST or MUST NOT be true. Look for: must, shall, required, mandatory, "
        "prohibited, forbidden, never, always.\n"
        "Ignore soft preferences, recommendations, and optional items.\n"
        "Tag each rule name with prefix 'c_' (e.g., c_min_age)."
    ),
    "exceptions": (
        "## Focus: Exceptions & Carve-Outs\n"
        "Extract ONLY rules that represent exceptions to general rules. "
        "Look for: unless, except, provided that, notwithstanding, however, "
        "in the event that, special case, exemption.\n"
        "For each exception, also note which general rule it modifies.\n"
        "Tag each rule name with prefix 'x_' (e.g., x_guarantor_override)."
    ),
    "definitions": (
        "## Focus: Definitions & Scope\n"
        "Extract ONLY rules that define entities, establish boundaries, or "
        "clarify what terms mean. Look for: is defined as, means, refers to, "
        "includes, excludes, for the purpose of.\n"
        "Prefer 'unique' rules for single-value definitions.\n"
        "Tag each rule name with prefix 'd_' (e.g., d_applicant_scope)."
    ),
    "boundaries": (
        "## Focus: Numeric Boundaries\n"
        "Extract ONLY rules involving numbers, dates, percentages, amounts, "
        "durations, or quantities. Look for: minimum, maximum, at least, "
        "at most, no more than, within N days, percentage.\n"
        "Prefer 'range' rules for bounded values.\n"
        "Tag each rule name with prefix 'b_' (e.g., b_max_loan_amount)."
    ),
    "adversarial": (
        "## Focus: Adversarial — Misinterpretation Prevention\n"
        "Read the document and ask: 'How could a careless reader or a "
        "language model misinterpret this?' For each potential misreading, "
        "write a rule that would CATCH the incorrect interpretation.\n\n"
        "Examples of misinterpretations to look for:\n"
        "- Confusing similar terms (e.g., 'net' vs 'gross' salary)\n"
        "- Applying a rule to the wrong entity\n"
        "- Missing implicit prerequisites\n"
        "- Assuming optional steps are mandatory (or vice versa)\n"
        "- Ignoring date/version boundaries\n"
        "Tag each rule name with prefix 'a_' (e.g., a_net_vs_gross)."
    ),
}

ALL_STRATEGIES = list(STRATEGY_DIRECTIVES.keys())


# =====================================================================
# Data Models
# =====================================================================


class CandidateRule(BaseModel):
    """A rule generated by one strategy — not yet approved."""

    id: int
    rule: Rule
    strategy: str
    source_excerpt: str = ""
    status: Literal[
        "pending",
        "in_conflict",
        "standalone",
        "approved",
        "rejected",
        "merged",
    ] = "pending"


class ArbitrationDecision(BaseModel):
    """A human's decision on a conflict."""

    conflict_id: int
    action: Literal["pick_winner", "reject_both", "rewrite", "approve_both"]
    winner_id: Optional[int] = None
    rewrite_rule: Optional[Dict[str, Any]] = None
    reason: str = ""
    decided_at: str = ""


class Conflict(BaseModel):
    """A group of candidates that interact with each other."""

    id: int
    type: Literal["contradiction", "redundancy", "subsumption", "gap"]
    candidate_ids: list[int]
    z3_result: str
    explanation: str
    resolution: Optional[ArbitrationDecision] = None


class TournamentAudit(BaseModel):
    """Complete record of a tournament for compliance/review."""

    domain: str
    source_document_hash: str
    generated_at: str
    strategies_used: list[str]
    total_candidates: int
    total_conflicts: int
    approved_count: int
    rejected_count: int
    rewritten_count: int
    candidates: list[CandidateRule]
    conflicts: list[Conflict]
    decisions: list[ArbitrationDecision]
    generation_warnings: list[str]


# =====================================================================
# Tournament Engine
# =====================================================================


class Tournament:
    """Tournament-style rule derivation engine.

    Generates competing candidate rules from a source document using
    multiple extraction strategies, detects conflicts using Z3, and
    lets humans arbitrate to produce approved .axiom.yml rules.
    """

    def __init__(
        self,
        source: str,
        domain: str = "tournament",
        strategies: Optional[List[str]] = None,
    ) -> None:
        self._source = source
        self._domain = domain
        self._strategies = strategies or ALL_STRATEGIES
        self._parser = AxiomParser()

        self._candidates: list[CandidateRule] = []
        self._conflicts: list[Conflict] = []
        self._decisions: list[ArbitrationDecision] = []
        self._generation_warnings: list[str] = []
        self._generated_at = ""

        # Validate strategies
        for s in self._strategies:
            if s not in STRATEGY_DIRECTIVES:
                raise ValueError(
                    f"Unknown strategy '{s}'. "
                    f"Available: {', '.join(ALL_STRATEGIES)}"
                )

    # =================================================================
    # Phase 1: Multi-Strategy Candidate Generation
    # =================================================================

    def generate(
        self,
        llm_generate: Callable[[str], str],
    ) -> None:
        """Generate candidates from all configured strategies.

        Each strategy sends the source document to the LLM with a different
        extraction focus directive. Results are parsed and validated.

        Args:
            llm_generate: A callable (str) -> str that calls an LLM.
        """
        self._generated_at = datetime.now(timezone.utc).isoformat()
        self._candidates = []
        self._conflicts = []
        self._decisions = []
        self._generation_warnings = []

        for strategy_name in self._strategies:
            directive = STRATEGY_DIRECTIVES[strategy_name]

            prompt = (
                f"{_RULE_GEN_PROMPT}\n\n"
                f"{directive}\n\n"
                f"## Domain\n{self._domain}\n\n"
                f"## Source Document\n\n{self._source}\n\n"
                f"Generate the .axiom.yml file now. Return ONLY valid YAML."
            )

            try:
                raw = llm_generate(prompt)
                yaml_str = _clean_yaml_output(raw)
                _validate_yaml(yaml_str)
                ruleset = self._parser.load_string(yaml_str)

                for rule in ruleset.rules:
                    self._candidates.append(CandidateRule(
                        id=len(self._candidates),
                        rule=rule,
                        strategy=strategy_name,
                    ))

            except Exception as e:
                self._generation_warnings.append(
                    f"Strategy '{strategy_name}' failed: {e}"
                )

    # =================================================================
    # Phase 2: Z3 Conflict Detection
    # =================================================================

    def detect_conflicts(self) -> list[Conflict]:
        """Run Z3-powered pairwise checks across all candidates.

        Detects contradictions (UNSAT), redundancies, subsumptions,
        and gaps (adversarial-only rules). Groups candidates by relation
        to reduce comparison space.

        Returns:
            List of detected conflicts.
        """
        self._conflicts = []

        # Group candidates by relation for efficient comparison
        groups = self._group_by_relation()

        for _relation, group in groups.items():
            for ca, cb in combinations(group, 2):
                # Skip if already resolved
                if ca.status not in ("pending", "standalone"):
                    if cb.status not in ("pending", "standalone"):
                        continue

                # Contradiction check
                if self._check_contradiction(ca.rule, cb.rule):
                    conflict = Conflict(
                        id=len(self._conflicts),
                        type="contradiction",
                        candidate_ids=[ca.id, cb.id],
                        z3_result="UNSAT",
                        explanation=(
                            f"'{ca.rule.name}' (strategy: {ca.strategy}) "
                            f"contradicts '{cb.rule.name}' (strategy: {cb.strategy}). "
                            f"Both cannot be true simultaneously."
                        ),
                    )
                    self._conflicts.append(conflict)
                    ca.status = "in_conflict"
                    cb.status = "in_conflict"
                    continue

                # Redundancy / subsumption check
                result = self._check_redundancy(ca.rule, cb.rule)
                if result is not None:
                    conflict_type = "redundancy" if result == "equivalent" else "subsumption"
                    conflict = Conflict(
                        id=len(self._conflicts),
                        type=conflict_type,
                        candidate_ids=[ca.id, cb.id],
                        z3_result=result,
                        explanation=self._explain_subsumption(ca, cb, result),
                    )
                    self._conflicts.append(conflict)
                    ca.status = "in_conflict"
                    cb.status = "in_conflict"

        # Detect gaps: adversarial found rules that no other strategy produced
        self._detect_gaps()

        # Mark non-conflicting candidates as standalone
        for c in self._candidates:
            if c.status == "pending":
                c.status = "standalone"

        return self._conflicts

    def _group_by_relation(self) -> dict[str, list[CandidateRule]]:
        """Group candidates by their primary relation for efficient comparison."""
        groups: dict[str, list[CandidateRule]] = {}
        for c in self._candidates:
            rel = self._primary_relation(c.rule)
            groups.setdefault(rel, []).append(c)
        return groups

    @staticmethod
    def _primary_relation(rule: Rule) -> str:
        """Extract the primary relation from a rule."""
        if isinstance(rule, (UniqueRule, ExclusionRule, RangeRule)):
            return rule.relation
        if isinstance(rule, DependencyRule):
            return rule.when.relation
        return ""

    def _check_contradiction(self, rule_a: Rule, rule_b: Rule) -> bool:
        """Check if two rules contradict each other using Z3.

        Creates a minimal KB with both rules and synthetic claims that
        exercise them. If UNSAT, they conflict.
        """
        kb = KnowledgeBase()
        try:
            kb.add_rule(rule_a)
            kb.add_rule(rule_b)
        except Exception:
            return False

        test_claims = self._synthetic_claims(rule_a, rule_b)
        if not test_claims:
            return False

        result = kb.verify(
            response_claims=test_claims,
            axiom_claims=[],
            timeout_ms=Z3_CONFLICT_TIMEOUT_MS,
        )
        return result.is_hallucinating

    def _check_redundancy(
        self, rule_a: Rule, rule_b: Rule
    ) -> Optional[str]:
        """Check if one rule makes the other redundant.

        Returns:
            "a_subsumes_b" — A is strictly stronger
            "b_subsumes_a" — B is strictly stronger
            "equivalent"   — Both produce identical results
            None           — Neither subsumes the other
        """
        test_claims = self._generate_test_suite(rule_a, rule_b)
        if not test_claims:
            return None

        kb_a = KnowledgeBase()
        kb_b = KnowledgeBase()
        try:
            kb_a.add_rule(rule_a)
            kb_b.add_rule(rule_b)
        except Exception:
            return None

        results_a = []
        results_b = []
        for claim_set in test_claims:
            ra = kb_a.verify(response_claims=claim_set, timeout_ms=Z3_REDUNDANCY_TIMEOUT_MS)
            rb = kb_b.verify(response_claims=claim_set, timeout_ms=Z3_REDUNDANCY_TIMEOUT_MS)
            results_a.append(ra.is_hallucinating)
            results_b.append(rb.is_hallucinating)

        if not results_a:
            return None

        if results_a == results_b:
            return "equivalent"

        a_catches_all_b = all(a or not b for a, b in zip(results_a, results_b))
        b_catches_all_a = all(b or not a for a, b in zip(results_a, results_b))

        if a_catches_all_b and not b_catches_all_a:
            return "a_subsumes_b"
        if b_catches_all_a and not a_catches_all_b:
            return "b_subsumes_a"

        return None

    def _synthetic_claims(self, rule_a: Rule, rule_b: Rule) -> list[Claim]:
        """Create minimal claims that exercise both rules simultaneously."""
        claims: list[Claim] = []
        entity = "test_entity"

        for rule in (rule_a, rule_b):
            claims.extend(self._claims_for_rule(rule, entity))

        # Deduplicate
        seen: set[tuple[str, str, str]] = set()
        unique: list[Claim] = []
        for c in claims:
            key = (c.subject, c.relation, c.object)
            if key not in seen:
                seen.add(key)
                unique.append(c)

        return unique

    @staticmethod
    def _claims_for_rule(rule: Rule, entity: str = "test_entity") -> list[Claim]:
        """Generate test claims that would trigger a specific rule."""
        claims: list[Claim] = []

        if isinstance(rule, UniqueRule):
            claims.append(Claim(subject=entity, relation=rule.relation, object="value_a"))
            claims.append(Claim(subject=entity, relation=rule.relation, object="value_b"))

        elif isinstance(rule, ExclusionRule):
            for val in rule.values:
                claims.append(Claim(subject=entity, relation=rule.relation, object=val))

        elif isinstance(rule, DependencyRule):
            claims.append(Claim(
                subject=entity,
                relation=rule.when.relation,
                object=rule.when.value,
            ))
            # Assert something that contradicts the 'then' requirement
            if rule.then.require.value:
                claims.append(Claim(
                    subject=entity,
                    relation=rule.then.require.relation,
                    object=f"not_{rule.then.require.value}",
                ))

        elif isinstance(rule, RangeRule):
            if rule.min is not None:
                claims.append(Claim(
                    subject=entity,
                    relation=rule.relation,
                    object=str(int(rule.min) - 1),
                ))
            elif rule.max is not None:
                claims.append(Claim(
                    subject=entity,
                    relation=rule.relation,
                    object=str(int(rule.max) + 1),
                ))

        return claims

    def _generate_test_suite(
        self, rule_a: Rule, rule_b: Rule
    ) -> list[list[Claim]]:
        """Generate multiple claim sets to compare two rules' behavior."""
        entity = "test_entity"
        suite: list[list[Claim]] = []

        # Test set 1: claims that trigger rule_a
        claims_a = self._claims_for_rule(rule_a, entity)
        if claims_a:
            suite.append(claims_a)

        # Test set 2: claims that trigger rule_b
        claims_b = self._claims_for_rule(rule_b, entity)
        if claims_b:
            suite.append(claims_b)

        # Test set 3: combined
        combined = claims_a + claims_b
        if combined:
            # Deduplicate
            seen: set[tuple[str, str, str]] = set()
            unique: list[Claim] = []
            for c in combined:
                key = (c.subject, c.relation, c.object)
                if key not in seen:
                    seen.add(key)
                    unique.append(c)
            suite.append(unique)

        return suite

    def _detect_gaps(self) -> None:
        """Detect relations covered only by adversarial strategy."""
        adversarial_rels: dict[str, list[CandidateRule]] = {}
        other_rels: set[str] = set()

        for c in self._candidates:
            rel = self._primary_relation(c.rule)
            if c.strategy == "adversarial":
                adversarial_rels.setdefault(rel, []).append(c)
            else:
                other_rels.add(rel)

        for rel, candidates in adversarial_rels.items():
            if rel not in other_rels:
                self._conflicts.append(Conflict(
                    id=len(self._conflicts),
                    type="gap",
                    candidate_ids=[c.id for c in candidates],
                    z3_result="N/A",
                    explanation=(
                        f"Adversarial strategy found rules for relation '{rel}' "
                        f"that no other strategy produced. This may indicate a "
                        f"gap in the document's explicit constraints."
                    ),
                ))

    @staticmethod
    def _explain_subsumption(
        ca: CandidateRule, cb: CandidateRule, result: str
    ) -> str:
        if result == "equivalent":
            return (
                f"'{ca.rule.name}' (strategy: {ca.strategy}) and "
                f"'{cb.rule.name}' (strategy: {cb.strategy}) are equivalent — "
                f"they produce identical verification results."
            )
        if result == "a_subsumes_b":
            return (
                f"'{ca.rule.name}' (strategy: {ca.strategy}) is strictly stronger than "
                f"'{cb.rule.name}' (strategy: {cb.strategy}). "
                f"Keeping only '{ca.rule.name}' is sufficient."
            )
        # b_subsumes_a
        return (
            f"'{cb.rule.name}' (strategy: {cb.strategy}) is strictly stronger than "
            f"'{ca.rule.name}' (strategy: {ca.strategy}). "
            f"Keeping only '{cb.rule.name}' is sufficient."
        )

    # =================================================================
    # Phase 3: Human Arbitration
    # =================================================================

    def decide(
        self,
        conflict_id: int,
        action: Literal["pick_winner", "reject_both", "rewrite", "approve_both"],
        winner_id: Optional[int] = None,
        rewrite_rule: Optional[Dict[str, Any]] = None,
        reason: str = "",
    ) -> None:
        """Record a human decision on a conflict.

        Args:
            conflict_id: Index into the conflicts list.
            action: What the human decided.
            winner_id: For "pick_winner" — which candidate wins.
            rewrite_rule: For "rewrite" — a raw YAML dict replacing both candidates.
            reason: Why the human made this decision (audit trail).

        Raises:
            ValueError: If conflict_id is invalid or action is inconsistent.
        """
        if conflict_id < 0 or conflict_id >= len(self._conflicts):
            raise ValueError(f"Invalid conflict_id: {conflict_id}")

        conflict = self._conflicts[conflict_id]

        decision = ArbitrationDecision(
            conflict_id=conflict_id,
            action=action,
            winner_id=winner_id,
            rewrite_rule=rewrite_rule,
            reason=reason,
            decided_at=datetime.now(timezone.utc).isoformat(),
        )

        if action == "pick_winner":
            if winner_id is None:
                raise ValueError("pick_winner requires winner_id")
            if winner_id not in conflict.candidate_ids:
                raise ValueError(
                    f"winner_id {winner_id} is not part of conflict "
                    f"{conflict.candidate_ids}"
                )
            for cid in conflict.candidate_ids:
                c = self._candidates[cid]
                if cid == winner_id:
                    c.status = "approved"
                else:
                    c.status = "rejected"

        elif action == "reject_both":
            for cid in conflict.candidate_ids:
                self._candidates[cid].status = "rejected"

        elif action == "rewrite":
            if rewrite_rule is None:
                raise ValueError("rewrite requires rewrite_rule dict")
            for cid in conflict.candidate_ids:
                self._candidates[cid].status = "merged"
            # Add rewrite as new approved candidate
            parsed = self._parse_single_rule(rewrite_rule)
            if parsed:
                self._candidates.append(CandidateRule(
                    id=len(self._candidates),
                    rule=parsed,
                    strategy="human_rewrite",
                    status="approved",
                ))

        elif action == "approve_both":
            for cid in conflict.candidate_ids:
                self._candidates[cid].status = "approved"

        conflict.resolution = decision
        self._decisions.append(decision)

    def approve(self, candidate_id: int) -> None:
        """Approve a standalone candidate."""
        self._validate_candidate_id(candidate_id)
        self._candidates[candidate_id].status = "approved"

    def reject(self, candidate_id: int, reason: str = "") -> None:
        """Reject a candidate."""
        self._validate_candidate_id(candidate_id)
        self._candidates[candidate_id].status = "rejected"

    def approve_all_standalone(self) -> int:
        """Approve all standalone (non-conflicting) candidates. Returns count."""
        count = 0
        for c in self._candidates:
            if c.status == "standalone":
                c.status = "approved"
                count += 1
        return count

    def _validate_candidate_id(self, candidate_id: int) -> None:
        if candidate_id < 0 or candidate_id >= len(self._candidates):
            raise ValueError(f"Invalid candidate_id: {candidate_id}")

    def _parse_single_rule(self, rule_dict: Dict[str, Any]) -> Optional[Rule]:
        """Parse a single rule dict into a Pydantic Rule object."""
        wrapper = {
            "axiomguard": "0.3",
            "domain": self._domain,
            "rules": [rule_dict],
        }
        try:
            ruleset = self._parser.load_string(
                yaml.dump(wrapper, allow_unicode=True, sort_keys=False)
            )
            return ruleset.rules[0]
        except Exception:
            return None

    # =================================================================
    # Phase 4: Export
    # =================================================================

    def to_knowledge_base(self) -> KnowledgeBase:
        """Export approved rules to a ready-to-use KnowledgeBase."""
        kb = KnowledgeBase()
        yaml_str = self.to_yaml()
        if yaml_str:
            kb.load_string(yaml_str)
        return kb

    def to_yaml(self) -> str:
        """Export approved rules as a .axiom.yml YAML string."""
        approved = [c for c in self._candidates if c.status == "approved"]
        if not approved:
            return ""

        rules_data: list[dict[str, Any]] = []
        for c in approved:
            rules_data.append(self._rule_to_dict(c.rule))

        data: dict[str, Any] = {
            "axiomguard": "0.3",
            "domain": self._domain,
            "rules": rules_data,
        }

        header = (
            f"# Generated by AxiomGuard Tournament Mode\n"
            f"# Source hash: {self._source_hash()}\n"
            f"# Strategies: {', '.join(self._strategies)}\n"
            f"# Candidates: {len(self._candidates)} generated, "
            f"{len(approved)} approved\n"
            f"# Generated: {self._generated_at}\n"
        )

        return header + yaml.dump(
            data, allow_unicode=True, sort_keys=False, default_flow_style=False
        )

    def to_file(self, path: str | Path) -> Path:
        """Export approved rules to a .axiom.yml file."""
        p = Path(path)
        yaml_str = self.to_yaml()
        if yaml_str:
            p.write_text(yaml_str, encoding="utf-8")
        return p

    def audit_trail(self) -> TournamentAudit:
        """Export full audit trail for compliance/review."""
        return TournamentAudit(
            domain=self._domain,
            source_document_hash=self._source_hash(),
            generated_at=self._generated_at,
            strategies_used=list(self._strategies),
            total_candidates=len(self._candidates),
            total_conflicts=len(self._conflicts),
            approved_count=sum(1 for c in self._candidates if c.status == "approved"),
            rejected_count=sum(1 for c in self._candidates if c.status == "rejected"),
            rewritten_count=sum(1 for c in self._candidates if c.status == "merged"),
            candidates=list(self._candidates),
            conflicts=list(self._conflicts),
            decisions=list(self._decisions),
            generation_warnings=list(self._generation_warnings),
        )

    @staticmethod
    def _rule_to_dict(rule: Rule) -> Dict[str, Any]:
        """Convert a Pydantic Rule back to a YAML-serializable dict."""
        return rule.model_dump(exclude_defaults=False, exclude_none=True)

    def _source_hash(self) -> str:
        return hashlib.sha256(self._source.encode("utf-8")).hexdigest()[:16]

    # =================================================================
    # Accessors
    # =================================================================

    @property
    def candidate_count(self) -> int:
        return len(self._candidates)

    def candidate(self, id: int) -> CandidateRule:
        """Get a candidate by ID."""
        self._validate_candidate_id(id)
        return self._candidates[id]

    def candidates(self, status: str | None = None) -> list[CandidateRule]:
        """Get candidates, optionally filtered by status."""
        if status is None:
            return list(self._candidates)
        return [c for c in self._candidates if c.status == status]

    def standalone_candidates(self) -> list[CandidateRule]:
        """Get all candidates with no conflicts (safe to batch-approve)."""
        return [c for c in self._candidates if c.status == "standalone"]

    def conflicts(self) -> list[Conflict]:
        """Get all detected conflicts."""
        return list(self._conflicts)

    @property
    def generation_warnings(self) -> list[str]:
        return list(self._generation_warnings)

    def summary(self) -> Dict[str, Any]:
        """Get a summary of the tournament state."""
        status_counts: dict[str, int] = {}
        for c in self._candidates:
            status_counts[c.status] = status_counts.get(c.status, 0) + 1

        strategy_counts: dict[str, int] = {}
        for c in self._candidates:
            strategy_counts[c.strategy] = strategy_counts.get(c.strategy, 0) + 1

        conflict_types: dict[str, int] = {}
        for conf in self._conflicts:
            conflict_types[conf.type] = conflict_types.get(conf.type, 0) + 1

        return {
            "domain": self._domain,
            "strategies": self._strategies,
            "total_candidates": len(self._candidates),
            "by_status": status_counts,
            "by_strategy": strategy_counts,
            "total_conflicts": len(self._conflicts),
            "by_conflict_type": conflict_types,
            "decisions_made": len(self._decisions),
            "unresolved_conflicts": sum(
                1 for c in self._conflicts if c.resolution is None
            ),
            "warnings": len(self._generation_warnings),
        }
