"""
AxiomGuard — Document to Rules Demo (AI-Generated)
====================================================

Shows how to convert a natural language policy document into
.axiom.yml rules using an LLM (Mode 2: AI-Generated).

Two options:
  A. With API key — uses Claude/GPT to generate real rules
  B. Without API key — uses a mock to show the workflow

Run:
    python examples/document_to_rules_demo.py

With real LLM:
    export ANTHROPIC_API_KEY="sk-ant-..."
    python examples/document_to_rules_demo.py
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from axiomguard import generate_rules, generate_rules_to_kb, RuleBuilder, Claim

# =====================================================================
# The source document (natural language policy)
# =====================================================================

COMPANY_POLICY = """
นโยบายสินเชื่อส่วนบุคคล บริษัท AxiomFinance

1. ผู้กู้ต้องมีอายุระหว่าง 20-60 ปี
2. เงินเดือนขั้นต่ำ 15,000 บาทต่อเดือน
3. อายุงานปัจจุบันไม่น้อยกว่า 6 เดือน
4. ห้ามมีประวัติค้างชำระเกิน 30 วัน
5. วงเงินกู้สูงสุดไม่เกิน 5 เท่าของเงินเดือน
6. สถานะการอนุมัติมีได้เพียงค่าเดียว (อนุมัติ หรือ ปฏิเสธ)
7. ผู้กู้แต่ละรายมีผู้รับผิดชอบสินเชื่อได้คนเดียว
"""

print("=" * 70)
print("  AxiomGuard — Document → Rules Demo")
print("=" * 70)
print()
print("--- Source Document ---")
print(COMPANY_POLICY)

# =====================================================================
# Option A: Try real LLM (if API key is available)
# =====================================================================

try:
    print("--- Mode 2: AI-Generated Rules ---")
    print("  Sending document to LLM...")
    print()

    yaml_str = generate_rules(
        text=COMPANY_POLICY,
        domain="personal_loan",
    )

    print("  Generated YAML:")
    print()
    for line in yaml_str.split("\n"):
        print(f"    {line}")
    print()
    print("  [OK] Rules generated by LLM successfully!")
    print()

    # Load into KnowledgeBase and verify
    kb = generate_rules_to_kb(
        text=COMPANY_POLICY,
        domain="personal_loan",
    )
    print(f"  KnowledgeBase ready: {kb.rule_count} rules, {kb.constraint_count} Z3 constraints")

except RuntimeError as e:
    # No API key available — show the workflow with mock
    print(f"  [SKIP] No LLM API key found. Showing mock workflow instead.")
    print(f"         Set ANTHROPIC_API_KEY or OPENAI_API_KEY to try real generation.")
    print()

    # =====================================================================
    # Option B: Mock — show what the output would look like
    # =====================================================================

    print("--- Mode 2 (Mock): What AI-Generated Rules Look Like ---")
    print()

    def mock_llm(prompt: str) -> str:
        """Simulates what an LLM would generate from the policy document."""
        return '''\
axiomguard: "0.3"
domain: personal_loan

entities:
  - name: applicant
    aliases: ["ผู้กู้", "ลูกค้า", "ผู้สมัคร"]

rules:
  - name: age_limit
    type: range
    entity: applicant
    relation: age
    value_type: int
    min: 20
    max: 60
    severity: error
    message: "ผู้กู้ต้องมีอายุระหว่าง 20-60 ปี"

  - name: min_salary
    type: range
    entity: applicant
    relation: salary_thb
    value_type: int
    min: 15000
    severity: error
    message: "เงินเดือนขั้นต่ำ 15,000 บาท"

  - name: min_employment
    type: range
    entity: applicant
    relation: employment_months
    value_type: int
    min: 6
    severity: error
    message: "อายุงานขั้นต่ำ 6 เดือน"

  - name: one_approval_status
    type: unique
    entity: applicant
    relation: approval_status
    severity: error
    message: "สถานะอนุมัติมีได้เพียงค่าเดียว"

  - name: one_loan_officer
    type: unique
    entity: applicant
    relation: loan_officer
    severity: error
    message: "ผู้รับผิดชอบสินเชื่อได้คนเดียว"
'''

    yaml_str = generate_rules(
        text=COMPANY_POLICY,
        domain="personal_loan",
        llm_generate=mock_llm,
    )

    print("  Generated YAML:")
    print()
    for line in yaml_str.split("\n"):
        print(f"    {line}")
    print()

    kb = generate_rules_to_kb(
        text=COMPANY_POLICY,
        domain="personal_loan",
        llm_generate=mock_llm,
    )
    print(f"  KnowledgeBase ready: {kb.rule_count} rules, {kb.constraint_count} Z3 constraints")

# =====================================================================
# Step 3: Verify against generated rules
# =====================================================================

print()
print("--- Verification with Generated Rules ---")
print()

test_cases = [
    ("Applicant salary 20,000 THB", [Claim(subject="applicant", relation="salary_thb", object="20000")]),
    ("Applicant salary 8,000 THB", [Claim(subject="applicant", relation="salary_thb", object="8000")]),
    ("Applicant age 35", [Claim(subject="applicant", relation="age", object="35")]),
    ("Applicant age 15", [Claim(subject="applicant", relation="age", object="15")]),
]

for desc, claims in test_cases:
    result = kb.verify(claims)
    status = "BLOCKED" if result.is_hallucinating else "OK"
    print(f"  [{status}] {desc}")
    if result.is_hallucinating:
        print(f"         {result.reason}")

print()

# =====================================================================
# Bonus: Mode 3 — Same rules built programmatically
# =====================================================================

print("--- Mode 3: Same Rules via RuleBuilder ---")
print()

builder = (
    RuleBuilder(domain="personal_loan")
    .entity("applicant", aliases=["ผู้กู้", "ลูกค้า"])
    .range_rule("age_limit", entity="applicant", relation="age",
                min=20, max=60, value_type="int")
    .range_rule("min_salary", entity="applicant", relation="salary_thb",
                min=15000, value_type="int")
    .unique("one_status", entity="applicant", relation="approval_status")
)

print(f"  RuleBuilder: {builder.rule_count} rules")
print(f"  YAML output length: {len(builder.to_yaml())} chars")
print()
print("  Both Mode 2 (AI) and Mode 3 (Code) produce the same result!")
print("  Choose whichever fits your workflow.")
